development:
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: db/development.sqlite3

production:
  adapter: postgresql
  encoding: unicode
  database: nyx_pg_prod
  pool: 5
  username: nyx
  password: root


